blank_issues_enabled: true
contact_links:
  - name: 💬 讨论区
    url: https://github.com/ZhuLinsen/daily_stock_analysis/discussions
    about: 有问题想讨论？欢迎来讨论区交流
  - name: 🔐 配置 Secrets 教程
    url: https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/how-to-configure-secrets.md
    about: 不知道如何配置 GitHub Secrets？查看详细图文教程
  - name: 📖 使用文档
    url: https://github.com/ZhuLinsen/daily_stock_analysis#-快速开始
    about: 查看 README 获取使用帮助
